### ISSUE TITLE
Error running configure.py

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/blasr_libcpp#61]
I get the following error running configure.py, and I'm not sure how to go about resolving:
note:
```
[mchaisso@e162 blasr_libcpp]$ uname -r
2.6.32-431.20.3.el6.x86_64

[mchaisso@e162 blasr_libcpp]$ ./configure.py
uname -s
uname='Linux'
bash -c 'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d
" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac' 2>/dev/null
Traceback (most recent call last):
  File "./configure.py", line 338, in <module>
    main(*sys.argv)
  File "./configure.py", line 334, in main
    configure_pacbio(envin)
  File "./configure.py", line 268, in configure_pacbio
    content1 = compose_defines_pacbio(envin)
  File "./configure.py", line 172, in compose_defines_pacbio
    setifenvf(env, envin, 'OS_STRING', get_OS_STRING)
  File "./configure.py", line 123, in setifenvf
    envout[key] = ifenvf(envin, key, func)
  File "./configure.py", line 121, in ifenvf
    return func()
  File "./configure.py", line 97, in get_OS_STRING
    return shell(G_BUILDOS_CMD)
  File "./configure.py", line 25, in shell
    raise Exception('%d <- %r' %(status, cmd))
Exception: 32512 <- 'bash -c \'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d\n" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac\' 2>/dev/null'
```

**Comment by pb-cdunn** [comment]
You need to pass some flags/args to configure.py. There are no useful defaults. See travis.sh.

**Comment by pb-cdunn** [comment]
Re-open if still an issue.

Also, if you strongly oppose any of the recent refactoring, please let us know now while we can still revert. (I personally wasn't happy about splitting Blasr.cpp into multiple files, but I also think that the primary package-maintainer deserves latitude. Otherwise, I generally like the refactoring myself.)

Currently, the tip of master here (blasr_libcpp) goes with p4-master in blasr. The blasr submodule specifies a consistent commit though. We'll rectify the branches when the refactoring is stable and all tests are passing.
